package com.pe.lima.sg.entity.operacion;
// default package
// Generated 17/06/2023 05:18:59 PM by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * TblFacturaAsociada generated by hbm2java
 */
@Entity
@Table(name = "tbl_factura_asociada", schema = "ope")
public class TblFacturaAsociada implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int codigoFacturaAsociada;
	private TblRemision tblRemision;
	private BigDecimal pesoTotal;
	private String observacion;
	private Integer codigoComprobante;
	private Set<TblDetalleRemision> tblDetalleRemisions = new HashSet<>(0);

	public TblFacturaAsociada() {
	}

	public TblFacturaAsociada(int codigoFacturaAsociada, TblRemision tblRemision) {
		this.codigoFacturaAsociada = codigoFacturaAsociada;
		this.tblRemision = tblRemision;
	}

	public TblFacturaAsociada(int codigoFacturaAsociada, TblRemision tblRemision, BigDecimal pesoTotal,
			String observacion, Integer codigoComprobante, Set<TblDetalleRemision> tblDetalleRemisions) {
		this.codigoFacturaAsociada = codigoFacturaAsociada;
		this.tblRemision = tblRemision;
		this.pesoTotal = pesoTotal;
		this.observacion = observacion;
		this.codigoComprobante = codigoComprobante;
		this.tblDetalleRemisions = tblDetalleRemisions;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "codigo_factura_asociada", unique = true, nullable = false)
	public int getCodigoFacturaAsociada() {
		return this.codigoFacturaAsociada;
	}

	public void setCodigoFacturaAsociada(int codigoFacturaAsociada) {
		this.codigoFacturaAsociada = codigoFacturaAsociada;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_remision", nullable = false)
	@JsonBackReference(value="tablaManage-TablaBack")
	public TblRemision getTblRemision() {
		return this.tblRemision;
	}

	public void setTblRemision(TblRemision tblRemision) {
		this.tblRemision = tblRemision;
	}

	@Column(name = "peso_total", precision = 10)
	public BigDecimal getPesoTotal() {
		return this.pesoTotal;
	}

	public void setPesoTotal(BigDecimal pesoTotal) {
		this.pesoTotal = pesoTotal;
	}

	@Column(name = "observacion", length = 216)
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	@Column(name = "codigo_comprobante")
	public Integer getCodigoComprobante() {
		return this.codigoComprobante;
	}

	public void setCodigoComprobante(Integer codigoComprobante) {
		this.codigoComprobante = codigoComprobante;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblFacturaAsociada")
	@JsonManagedReference(value="tablaManage-TablaBack")
	public Set<TblDetalleRemision> getTblDetalleRemisions() {
		return this.tblDetalleRemisions;
	}

	public void setTblDetalleRemisions(Set<TblDetalleRemision> tblDetalleRemisions) {
		this.tblDetalleRemisions = tblDetalleRemisions;
	}

}
