package com.pe.lima.sg.entity.operacion;
// Generated 17/06/2023 05:18:59 PM by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.servlet.http.HttpServletRequest;

import com.fasterxml.jackson.annotation.JsonManagedReference;
import com.pe.lima.sg.presentacion.util.Constantes;

/**
 * TblRemision generated by hbm2java
 */
@Entity
@Table(name = "tbl_remision", schema = "ope")
public class TblRemision implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int codigoRemision;
	private String motivoTraslado;
	private String codigoDomicilioPartida;
	private String domicilioLlegada;
	private String fechaEmision;
	private String fechaInicioTraslado;
	private String horaInicioTraslado;
	private String tipoComprobante;
	private String serie;
	private String numero;
	private String tipoDocumentoCliente;
	private String numeroDocumentoCliente;
	private String nombreCliente;
	private String tipoDocumentoTransportista;
	private String numeroDocumentoTransportista;
	private String nombreTransportista;
	private String vehiculo;
	private String marca;
	private String placa;
	private String numeroCertInscripcion;
	private String numeroLicencia;
	private BigDecimal pesoTotal;
	private String estado;
	private Date fechaCreacion;
	private Date fechaModificacion;
	private Integer usuarioCreacion;
	private Integer usuarioModificacion;
	private String ipModificacion;
	private String ipCreacion;
	private String estadoOperacion;
	private Integer codigoEntidad;
	private String versionUbl;
	private String customizacionDoc;
	private String observacion;
	private String ticket;
	private Set<TblFacturaAsociada> tblFacturaAsociadas = new HashSet<>(0);

	public TblRemision() {
	}

	public TblRemision(int codigoRemision) {
		this.codigoRemision = codigoRemision;
	}

	public TblRemision(int codigoRemision, String motivoTraslado, String codigoDomicilioPartida,
			String domicilioLlegada, String fechaEmision, String fechaInicioTraslado, String horaInicioTraslado,
			String tipoComprobante, String serie, String numero, String tipoDocumentoCliente,
			String numeroDocumentoCliente, String nombreCliente, String tipoDocumentoTransportista,
			String numeroDocumentoTransportista, String nombreTransportista, String vehiculo, String marca,
			String placa, String numeroCertInscripcion, String numeroLicencia, BigDecimal pesoTotal, String estado,
			Date fechaCreacion, Date fechaModificacion, Integer usuarioCreacion, Integer usuarioModificacion,
			String ipModificacion, String ipCreacion, String estadoOperacion, Integer codigoEntidad, String versionUbl,
			String customizacionDoc, String observacion, String ticket, Set<TblFacturaAsociada> tblFacturaAsociadas) {
		this.codigoRemision = codigoRemision;
		this.motivoTraslado = motivoTraslado;
		this.codigoDomicilioPartida = codigoDomicilioPartida;
		this.domicilioLlegada = domicilioLlegada;
		this.fechaEmision = fechaEmision;
		this.fechaInicioTraslado = fechaInicioTraslado;
		this.horaInicioTraslado = horaInicioTraslado;
		this.tipoComprobante = tipoComprobante;
		this.serie = serie;
		this.numero = numero;
		this.tipoDocumentoCliente = tipoDocumentoCliente;
		this.numeroDocumentoCliente = numeroDocumentoCliente;
		this.nombreCliente = nombreCliente;
		this.tipoDocumentoTransportista = tipoDocumentoTransportista;
		this.numeroDocumentoTransportista = numeroDocumentoTransportista;
		this.nombreTransportista = nombreTransportista;
		this.vehiculo = vehiculo;
		this.marca = marca;
		this.placa = placa;
		this.numeroCertInscripcion = numeroCertInscripcion;
		this.numeroLicencia = numeroLicencia;
		this.pesoTotal = pesoTotal;
		this.estado = estado;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
		this.usuarioCreacion = usuarioCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.ipModificacion = ipModificacion;
		this.ipCreacion = ipCreacion;
		this.estadoOperacion = estadoOperacion;
		this.codigoEntidad = codigoEntidad;
		this.versionUbl = versionUbl;
		this.customizacionDoc = customizacionDoc;
		this.observacion = observacion;
		this.ticket = ticket;
		this.tblFacturaAsociadas = tblFacturaAsociadas;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "codigo_remision", unique = true, nullable = false)
	public int getCodigoRemision() {
		return this.codigoRemision;
	}

	public void setCodigoRemision(int codigoRemision) {
		this.codigoRemision = codigoRemision;
	}

	@Column(name = "motivo_traslado", length = 8)
	public String getMotivoTraslado() {
		return this.motivoTraslado;
	}

	public void setMotivoTraslado(String motivoTraslado) {
		this.motivoTraslado = motivoTraslado;
	}

	@Column(name = "codigo_domicilio_partida", length = 8)
	public String getCodigoDomicilioPartida() {
		return this.codigoDomicilioPartida;
	}

	public void setCodigoDomicilioPartida(String codigoDomicilioPartida) {
		this.codigoDomicilioPartida = codigoDomicilioPartida;
	}

	@Column(name = "domicilio_llegada", length = 512)
	public String getDomicilioLlegada() {
		return this.domicilioLlegada;
	}

	public void setDomicilioLlegada(String domicilioLlegada) {
		this.domicilioLlegada = domicilioLlegada;
	}

	@Column(name = "fecha_emision", length = 10)
	public String getFechaEmision() {
		return this.fechaEmision;
	}

	public void setFechaEmision(String fechaEmision) {
		this.fechaEmision = fechaEmision;
	}

	@Column(name = "fecha_inicio_traslado", length = 10)
	public String getFechaInicioTraslado() {
		return this.fechaInicioTraslado;
	}

	public void setFechaInicioTraslado(String fechaInicioTraslado) {
		this.fechaInicioTraslado = fechaInicioTraslado;
	}

	@Column(name = "hora_inicio_traslado", length = 8)
	public String getHoraInicioTraslado() {
		return this.horaInicioTraslado;
	}

	public void setHoraInicioTraslado(String horaInicioTraslado) {
		this.horaInicioTraslado = horaInicioTraslado;
	}

	@Column(name = "tipo_comprobante", length = 8)
	public String getTipoComprobante() {
		return this.tipoComprobante;
	}

	public void setTipoComprobante(String tipoComprobante) {
		this.tipoComprobante = tipoComprobante;
	}

	@Column(name = "serie", length = 8)
	public String getSerie() {
		return this.serie;
	}

	public void setSerie(String serie) {
		this.serie = serie;
	}

	@Column(name = "numero", length = 16)
	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	@Column(name = "tipo_documento_cliente", length = 8)
	public String getTipoDocumentoCliente() {
		return this.tipoDocumentoCliente;
	}

	public void setTipoDocumentoCliente(String tipoDocumentoCliente) {
		this.tipoDocumentoCliente = tipoDocumentoCliente;
	}

	@Column(name = "numero_documento_cliente", length = 32)
	public String getNumeroDocumentoCliente() {
		return this.numeroDocumentoCliente;
	}

	public void setNumeroDocumentoCliente(String numeroDocumentoCliente) {
		this.numeroDocumentoCliente = numeroDocumentoCliente;
	}

	@Column(name = "nombre_cliente", length = 512)
	public String getNombreCliente() {
		return this.nombreCliente;
	}

	public void setNombreCliente(String nombreCliente) {
		this.nombreCliente = nombreCliente;
	}

	@Column(name = "tipo_documento_transportista", length = 8)
	public String getTipoDocumentoTransportista() {
		return this.tipoDocumentoTransportista;
	}

	public void setTipoDocumentoTransportista(String tipoDocumentoTransportista) {
		this.tipoDocumentoTransportista = tipoDocumentoTransportista;
	}

	@Column(name = "numero_documento_transportista", length = 32)
	public String getNumeroDocumentoTransportista() {
		return this.numeroDocumentoTransportista;
	}

	public void setNumeroDocumentoTransportista(String numeroDocumentoTransportista) {
		this.numeroDocumentoTransportista = numeroDocumentoTransportista;
	}

	@Column(name = "nombre_transportista", length = 512)
	public String getNombreTransportista() {
		return this.nombreTransportista;
	}

	public void setNombreTransportista(String nombreTransportista) {
		this.nombreTransportista = nombreTransportista;
	}

	@Column(name = "vehiculo", length = 216)
	public String getVehiculo() {
		return this.vehiculo;
	}

	public void setVehiculo(String vehiculo) {
		this.vehiculo = vehiculo;
	}

	@Column(name = "marca", length = 128)
	public String getMarca() {
		return this.marca;
	}

	public void setMarca(String marca) {
		this.marca = marca;
	}

	@Column(name = "placa", length = 64)
	public String getPlaca() {
		return this.placa;
	}

	public void setPlaca(String placa) {
		this.placa = placa;
	}

	@Column(name = "numero_cert_inscripcion", length = 64)
	public String getNumeroCertInscripcion() {
		return this.numeroCertInscripcion;
	}

	public void setNumeroCertInscripcion(String numeroCertInscripcion) {
		this.numeroCertInscripcion = numeroCertInscripcion;
	}

	@Column(name = "numero_licencia", length = 64)
	public String getNumeroLicencia() {
		return this.numeroLicencia;
	}

	public void setNumeroLicencia(String numeroLicencia) {
		this.numeroLicencia = numeroLicencia;
	}

	@Column(name = "peso_total", precision = 12)
	public BigDecimal getPesoTotal() {
		return this.pesoTotal;
	}

	public void setPesoTotal(BigDecimal pesoTotal) {
		this.pesoTotal = pesoTotal;
	}

	@Column(name = "estado", length = 1)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_creacion", length = 29)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 29)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "usuario_creacion")
	public Integer getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(Integer usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Column(name = "usuario_modificacion")
	public Integer getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(Integer usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Column(name = "ip_modificacion", length = 64)
	public String getIpModificacion() {
		return this.ipModificacion;
	}

	public void setIpModificacion(String ipModificacion) {
		this.ipModificacion = ipModificacion;
	}

	@Column(name = "ip_creacion", length = 64)
	public String getIpCreacion() {
		return this.ipCreacion;
	}

	public void setIpCreacion(String ipCreacion) {
		this.ipCreacion = ipCreacion;
	}

	@Column(name = "estado_operacion", length = 8)
	public String getEstadoOperacion() {
		return this.estadoOperacion;
	}

	public void setEstadoOperacion(String estadoOperacion) {
		this.estadoOperacion = estadoOperacion;
	}

	@Column(name = "codigo_entidad")
	public Integer getCodigoEntidad() {
		return this.codigoEntidad;
	}

	public void setCodigoEntidad(Integer codigoEntidad) {
		this.codigoEntidad = codigoEntidad;
	}

	@Column(name = "version_ubl", length = 8)
	public String getVersionUbl() {
		return this.versionUbl;
	}

	public void setVersionUbl(String versionUbl) {
		this.versionUbl = versionUbl;
	}

	@Column(name = "customizacion_doc", length = 8)
	public String getCustomizacionDoc() {
		return this.customizacionDoc;
	}

	public void setCustomizacionDoc(String customizacionDoc) {
		this.customizacionDoc = customizacionDoc;
	}

	@Column(name = "observacion", length = 256)
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	@Column(name = "ticket", length = 256)
	public String getTicket() {
		return this.ticket;
	}

	public void setTicket(String ticket) {
		this.ticket = ticket;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblRemision")
	@JsonManagedReference(value="tablaManage-TablaBack")
	public Set<TblFacturaAsociada> getTblFacturaAsociadas() {
		return this.tblFacturaAsociadas;
	}

	public void setTblFacturaAsociadas(Set<TblFacturaAsociada> tblFacturaAsociadas) {
		this.tblFacturaAsociadas = tblFacturaAsociadas;
	}

	public void setAuditoriaCreacion(HttpServletRequest request){
		Integer idUsuario 		= null;
		String strIdUsuario 	= null;
		try{
			this.setFechaCreacion(new Date(System.currentTimeMillis()));
			this.setIpCreacion(request.getRemoteAddr());
			this.setEstado(Constantes.ESTADO_REGISTRO_ACTIVO);
			strIdUsuario = (String)request.getSession().getAttribute("id_usuario");
			if (strIdUsuario==null){
				idUsuario = 1;
			}else{
				idUsuario = new Integer(strIdUsuario);
			}
			this.setUsuarioCreacion(idUsuario);
		}catch(Exception e){
			e.printStackTrace();
			this.setUsuarioCreacion(0);
		}finally{
			idUsuario 		= null;
			strIdUsuario	= null;
		}
	}
	
	public void setAuditoriaModificacion(HttpServletRequest request){
		Integer idUsuario 		= null;
		String strIdUsuario 	= null;
		try{
			this.setFechaModificacion(new Date(System.currentTimeMillis()));
			this.setIpModificacion(request.getRemoteAddr());
			strIdUsuario = (String)request.getSession().getAttribute("id_usuario");
			if (strIdUsuario==null){
				idUsuario = 1;
			}else{
				idUsuario = new Integer(strIdUsuario);
			}
			this.setUsuarioModificacion(idUsuario);
		}catch(Exception e){
			e.printStackTrace();
			this.setUsuarioModificacion(0);
		}finally{
			idUsuario 		= null;
			strIdUsuario	= null;
		}
	}
}

