package com.pe.lima.sg.entity.mantenimiento;
// Generated 17/12/2017 10:06:23 AM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * TblCatalogo generated by hbm2java
 */
@Entity
@Table(name = "tbl_catalogo", schema = "mae")
public class TblCatalogo implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private int codigoCatalogo;
	private TblTipoCatalogo tblTipoCatalogo;
	private String codigoSunat;
	private String nombre;
	private String descripcion;
	private String estado;
	private Integer usuarioCreacion;
	private Integer usuarioModificacion;
	private Date fechaCreacion;
	private Date fechaModificacion;
	private String ipCreacion;
	private String ipModificacion;
	private Set<TblCliente> tblClientes = new HashSet<TblCliente>(0);
	private Set<TblProducto> tblProductos = new HashSet<TblProducto>(0);
	private Integer codigoEmpresa;

	public TblCatalogo() {
	}

	public TblCatalogo(int codigoCatalogo, TblTipoCatalogo tblTipoCatalogo) {
		this.codigoCatalogo = codigoCatalogo;
		this.tblTipoCatalogo = tblTipoCatalogo;
	}

	public TblCatalogo(int codigoCatalogo, TblTipoCatalogo tblTipoCatalogo, String codigoSunat, String nombre,
			String descripcion, String estado, Integer usuarioCreacion, Integer usuarioModificacion, Date fechaCreacion,
			Date fechaModificacion, String ipCreacion, String ipModificacion, Set<TblCliente> tblClientes, Set<TblProducto> tblProductos) {
		this.codigoCatalogo = codigoCatalogo;
		this.tblTipoCatalogo = tblTipoCatalogo;
		this.codigoSunat = codigoSunat;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.estado = estado;
		this.usuarioCreacion = usuarioCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
		this.ipCreacion = ipCreacion;
		this.ipModificacion = ipModificacion;
		this.tblClientes = tblClientes;
		this.tblProductos = tblProductos;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "codigo_catalogo", unique = true, nullable = false)
	public int getCodigoCatalogo() {
		return this.codigoCatalogo;
	}

	public void setCodigoCatalogo(int codigoCatalogo) {
		this.codigoCatalogo = codigoCatalogo;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "codigo_tipo_catalogo", nullable = false)
	@JsonBackReference(value="tablaManage-TablaBack")
	public TblTipoCatalogo getTblTipoCatalogo() {
		return this.tblTipoCatalogo;
	}

	public void setTblTipoCatalogo(TblTipoCatalogo tblTipoCatalogo) {
		this.tblTipoCatalogo = tblTipoCatalogo;
	}

	@Column(name = "codigo_sunat", length = 8)
	public String getCodigoSunat() {
		return this.codigoSunat;
	}

	public void setCodigoSunat(String codigoSunat) {
		this.codigoSunat = codigoSunat;
	}

	@Column(name = "nombre", length = 256)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 512)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "estado", length = 1)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "usuario_creacion")
	public Integer getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(Integer usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Column(name = "usuario_modificacion")
	public Integer getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(Integer usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_creacion", length = 29)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 29)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "ip_creacion", length = 64)
	public String getIpCreacion() {
		return this.ipCreacion;
	}

	public void setIpCreacion(String ipCreacion) {
		this.ipCreacion = ipCreacion;
	}

	@Column(name = "ip_modificacion", length = 64)
	public String getIpModificacion() {
		return this.ipModificacion;
	}

	public void setIpModificacion(String ipModificacion) {
		this.ipModificacion = ipModificacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblCatalogo")
	@JsonManagedReference(value="tablaManage-TablaBack")
	public Set<TblCliente> getTblClientes() {
		return this.tblClientes;
	}

	public void setTblClientes(Set<TblCliente> tblClientes) {
		this.tblClientes = tblClientes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblCatalogo")
	@JsonManagedReference(value="tablaManage-TablaBack")
	public Set<TblProducto> getTblProductos() {
		return this.tblProductos;
	}

	public void setTblProductos(Set<TblProducto> tblProductos) {
		this.tblProductos = tblProductos;
	}

	@Column(name = "codigo_entidad")
	public Integer getCodigoEmpresa() {
		return codigoEmpresa;
	}

	public void setCodigoEmpresa(Integer codigoEmpresa) {
		this.codigoEmpresa = codigoEmpresa;
	}

}
