package com.pe.lima.sg.entity.mantenimiento;
// Generated 17/12/2017 10:06:23 AM by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * TblProducto generated by hbm2java
 */
@Entity
@Table(name = "tbl_producto", schema = "mae")
public class TblProducto implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private int codigoProducto;
	private TblCatalogo tblCatalogo;
	private String codigoEmpresa;
	private String codigoSunat;
	private String nombre;
	private BigDecimal precio;
	private String estado;
	private Date fechaCreacion;
	private Date fechaModificacion;
	private Integer usuarioCreacion;
	private Integer usuarioModificacion;
	private String ipCreacion;
	private String ipModificacion;
	private TblEmpresa tblEmpresa;
	private BigDecimal peso;
	private String unidadMedida;

	public TblProducto() {
	}

	public TblProducto(int codigoProducto, TblCatalogo tblCatalogo) {
		this.codigoProducto = codigoProducto;
		this.tblCatalogo = tblCatalogo;
	}

	public TblProducto(int codigoProducto, TblCatalogo tblCatalogo, String codigoEmpresa, String codigoSunat,
			String nombre, BigDecimal precio, String estado, Date fechaCreacion, Date fechaModificacion,
			Integer usuarioCreacion, Integer usuarioModificacion, String ipCreacion, String ipModificacion, TblEmpresa tblEmpresa) {
		this.codigoProducto = codigoProducto;
		this.tblCatalogo = tblCatalogo;
		this.codigoEmpresa = codigoEmpresa;
		this.codigoSunat = codigoSunat;
		this.nombre = nombre;
		this.precio = precio;
		this.estado = estado;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
		this.usuarioCreacion = usuarioCreacion;
		this.usuarioModificacion = usuarioModificacion;
		this.ipCreacion = ipCreacion;
		this.ipModificacion = ipModificacion;
		this.tblEmpresa = tblEmpresa;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "codigo_producto", unique = true, nullable = false)
	@JsonBackReference(value="tablaManage-TablaBack")
	public int getCodigoProducto() {
		return this.codigoProducto;
	}

	public void setCodigoProducto(int codigoProducto) {
		this.codigoProducto = codigoProducto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_catalogo", nullable = false)
	@JsonBackReference(value="tablaManage-TablaBack")
	public TblCatalogo getTblCatalogo() {
		return this.tblCatalogo;
	}

	public void setTblCatalogo(TblCatalogo tblCatalogo) {
		this.tblCatalogo = tblCatalogo;
	}

	@Column(name = "codigo_empresa", length = 32)
	public String getCodigoEmpresa() {
		return this.codigoEmpresa;
	}

	public void setCodigoEmpresa(String codigoEmpresa) {
		this.codigoEmpresa = codigoEmpresa;
	}

	@Column(name = "codigo_sunat", length = 36)
	public String getCodigoSunat() {
		return this.codigoSunat;
	}

	public void setCodigoSunat(String codigoSunat) {
		this.codigoSunat = codigoSunat;
	}

	@Column(name = "nombre", length = 256)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "precio", precision = 12)
	public BigDecimal getPrecio() {
		return this.precio;
	}

	public void setPrecio(BigDecimal precio) {
		this.precio = precio;
	}

	@Column(name = "estado", length = 1)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_creacion", length = 29)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", length = 29)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "usuario_creacion")
	public Integer getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(Integer usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Column(name = "usuario_modificacion")
	public Integer getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	public void setUsuarioModificacion(Integer usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Column(name = "ip_creacion", length = 64)
	public String getIpCreacion() {
		return this.ipCreacion;
	}

	public void setIpCreacion(String ipCreacion) {
		this.ipCreacion = ipCreacion;
	}

	@Column(name = "ip_modificacion", length = 64)
	public String getIpModificacion() {
		return this.ipModificacion;
	}

	public void setIpModificacion(String ipModificacion) {
		this.ipModificacion = ipModificacion;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "codigo_entidad", nullable = false)
	@JsonBackReference(value="tablaManage-TablaBack")
	public TblEmpresa getTblEmpresa() {
		return this.tblEmpresa;
	}

	public void setTblEmpresa(TblEmpresa tblEmpresa) {
		this.tblEmpresa = tblEmpresa;
	}

	@Column(name = "peso", precision = 10)
	public BigDecimal getPeso() {
		return peso;
	}

	public void setPeso(BigDecimal peso) {
		this.peso = peso;
	}

	@Column(name = "unidad_medida", length = 32)
	public String getUnidadMedida() {
		return unidadMedida;
	}

	public void setUnidadMedida(String unidadMedida) {
		this.unidadMedida = unidadMedida;
	}
}
